//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5472
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer.Layout.Basic {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.ImageViewer.Layout.Basic.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Explode Tile 的本地化字符串。
        /// </summary>
        public static string CommandExplodeTile {
            get {
                return ResourceManager.GetString("CommandExplodeTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置序列窗格 的本地化字符串。
        /// </summary>
        public static string CommandLayoutImageBoxes {
            get {
                return ResourceManager.GetString("CommandLayoutImageBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置图像窗格 的本地化字符串。
        /// </summary>
        public static string CommandLayoutTiles {
            get {
                return ResourceManager.GetString("CommandLayoutTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收缩/展开 的本地化字符串。
        /// </summary>
        public static string CommandSurveyExplode {
            get {
                return ResourceManager.GetString("CommandSurveyExplode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (List of Display Sets) 的本地化字符串。
        /// </summary>
        public static string DisplaySets {
            get {
                return ResourceManager.GetString("DisplaySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified image is not currently loaded (SopInstanceUID={0}). 的本地化字符串。
        /// </summary>
        public static string ExceptionImageNotLoaded {
            get {
                return ResourceManager.GetString("ExceptionImageNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified series is not currently loaded (SeriesInstanceUID={0}). 的本地化字符串。
        /// </summary>
        public static string ExceptionSeriesNotLoaded {
            get {
                return ResourceManager.GetString("ExceptionSeriesNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified study is not currently loaded (StudyInstanceUID={0}). 的本地化字符串。
        /// </summary>
        public static string ExceptionStudyNotLoaded {
            get {
                return ResourceManager.GetString("ExceptionStudyNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 in use 的本地化字符串。
        /// </summary>
        public static string InUse {
            get {
                return ResourceManager.GetString("InUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create single image display sets 的本地化字符串。
        /// </summary>
        public static string LabelCreateSingleImageDisplaySets {
            get {
                return ResourceManager.GetString("LabelCreateSingleImageDisplaySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Default) 的本地化字符串。
        /// </summary>
        public static string LabelDefault {
            get {
                return ResourceManager.GetString("LabelDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The study is {0}. 的本地化字符串。
        /// </summary>
        public static string LabelFormatStudyUnavailable {
            get {
                return ResourceManager.GetString("LabelFormatStudyUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading Priors ... 的本地化字符串。
        /// </summary>
        public static string LabelLoadingPriors {
            get {
                return ResourceManager.GetString("LabelLoadingPriors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Split multi-echo series 的本地化字符串。
        /// </summary>
        public static string LabelSplitEchos {
            get {
                return ResourceManager.GetString("LabelSplitEchos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Split mixed mult-frame series 的本地化字符串。
        /// </summary>
        public static string LabelSplitMultiframes {
            get {
                return ResourceManager.GetString("LabelSplitMultiframes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The study could not be loaded. 的本地化字符串。
        /// </summary>
        public static string LabelStudyCouldNotBeLoaded {
            get {
                return ResourceManager.GetString("LabelStudyCouldNotBeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收缩/展开 的本地化字符串。
        /// </summary>
        public static string MenuExplodeImageBox {
            get {
                return ResourceManager.GetString("MenuExplodeImageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗格设置 的本地化字符串。
        /// </summary>
        public static string MenuLayoutManager {
            get {
                return ResourceManager.GetString("MenuLayoutManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一个序列 的本地化字符串。
        /// </summary>
        public static string MenuNextDisplaySet {
            get {
                return ResourceManager.GetString("MenuNextDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一个序列 的本地化字符串。
        /// </summary>
        public static string MenuPreviousDisplaySet {
            get {
                return ResourceManager.GetString("MenuPreviousDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show/Hide &amp;Colour Bar 的本地化字符串。
        /// </summary>
        public static string MenuShowHideColorBar {
            get {
                return ResourceManager.GetString("MenuShowHideColorBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show/Hide DICOM Overlay(s) 的本地化字符串。
        /// </summary>
        public static string MenuShowHideDicomOverlay {
            get {
                return ResourceManager.GetString("MenuShowHideDicomOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show/Hide Scale Overlay 的本地化字符串。
        /// </summary>
        public static string MenuShowHideScaleOverlay {
            get {
                return ResourceManager.GetString("MenuShowHideScaleOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show/Hide Shutter Overlay 的本地化字符串。
        /// </summary>
        public static string MenuShowHideShutterOverlay {
            get {
                return ResourceManager.GetString("MenuShowHideShutterOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show/Hide Text Overlay 的本地化字符串。
        /// </summary>
        public static string MenuShowHideTextOverlay {
            get {
                return ResourceManager.GetString("MenuShowHideTextOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准 的本地化字符串。
        /// </summary>
        public static string MenuStandard {
            get {
                return ResourceManager.GetString("MenuStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The following errors occurred while loading prior studies: 的本地化字符串。
        /// </summary>
        public static string MessageLoadPriorsErrorPrefix {
            get {
                return ResourceManager.GetString("MessageLoadPriorsErrorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The search for prior studies did not complete successfully because at least one of your default servers was unreachable.
        ///Although some priors may be available, please be aware that you may be working with an incomplete patient history.
        ///
        ///PLEASE NOTE that you will NOT be notified of this problem again for as long as this problem persists. 的本地化字符串。
        /// </summary>
        public static string MessagePriorsIncomplete {
            get {
                return ResourceManager.GetString("MessagePriorsIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The search for prior studies has failed.  Try reopening the study or select a different default server.
        ///
        ///PLEASE NOTE that you will NOT be notified of this problem again for as long as this problem persists. 的本地化字符串。
        /// </summary>
        public static string MessageSearchForPriorsFailed {
            get {
                return ResourceManager.GetString("MessageSearchForPriorsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color Bar 的本地化字符串。
        /// </summary>
        public static string NameColourBarOverlay {
            get {
                return ResourceManager.GetString("NameColourBarOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DICOM 的本地化字符串。
        /// </summary>
        public static string NameDicomOverlay {
            get {
                return ResourceManager.GetString("NameDicomOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scale 的本地化字符串。
        /// </summary>
        public static string NameScaleOverlay {
            get {
                return ResourceManager.GetString("NameScaleOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shutter 的本地化字符串。
        /// </summary>
        public static string NameShutterOverlay {
            get {
                return ResourceManager.GetString("NameShutterOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text 的本地化字符串。
        /// </summary>
        public static string NameTextOverlay {
            get {
                return ResourceManager.GetString("NameTextOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 nearline 的本地化字符串。
        /// </summary>
        public static string Nearline {
            get {
                return ResourceManager.GetString("Nearline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 offline 的本地化字符串。
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像序列设置 的本地化字符串。
        /// </summary>
        public static string TitleDisplaySetCreationConfiguration {
            get {
                return ResourceManager.GetString("TitleDisplaySetCreationConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗格设置 的本地化字符串。
        /// </summary>
        public static string TitleLayoutConfiguration {
            get {
                return ResourceManager.GetString("TitleLayoutConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Layout Manager 的本地化字符串。
        /// </summary>
        public static string TitleLayoutManager {
            get {
                return ResourceManager.GetString("TitleLayoutManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Layout 的本地化字符串。
        /// </summary>
        public static string ToolbarChangeLayout {
            get {
                return ResourceManager.GetString("ToolbarChangeLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Colour Bar 的本地化字符串。
        /// </summary>
        public static string ToolbarColorBar {
            get {
                return ResourceManager.GetString("ToolbarColorBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DICOM Overlay(s) 的本地化字符串。
        /// </summary>
        public static string ToolbarDicomOverlay {
            get {
                return ResourceManager.GetString("ToolbarDicomOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Survey/Explode 的本地化字符串。
        /// </summary>
        public static string ToolbarExplodeImageBox {
            get {
                return ResourceManager.GetString("ToolbarExplodeImageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Box Layout 的本地化字符串。
        /// </summary>
        public static string ToolbarLayoutBoxesChooser {
            get {
                return ResourceManager.GetString("ToolbarLayoutBoxesChooser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tile Layout 的本地化字符串。
        /// </summary>
        public static string ToolbarLayoutTilesChooser {
            get {
                return ResourceManager.GetString("ToolbarLayoutTilesChooser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next Display Set 的本地化字符串。
        /// </summary>
        public static string ToolbarNextDisplaySet {
            get {
                return ResourceManager.GetString("ToolbarNextDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous Display Set 的本地化字符串。
        /// </summary>
        public static string ToolbarPreviousDisplaySet {
            get {
                return ResourceManager.GetString("ToolbarPreviousDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scale Overlay 的本地化字符串。
        /// </summary>
        public static string ToolbarScaleOverlay {
            get {
                return ResourceManager.GetString("ToolbarScaleOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show/Hide Overlays 的本地化字符串。
        /// </summary>
        public static string ToolbarShowHideOverlays {
            get {
                return ResourceManager.GetString("ToolbarShowHideOverlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shutter Overlay 的本地化字符串。
        /// </summary>
        public static string ToolbarShutterOverlay {
            get {
                return ResourceManager.GetString("ToolbarShutterOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text 覆盖 的本地化字符串。
        /// </summary>
        public static string ToolbarTextOverlay {
            get {
                return ResourceManager.GetString("ToolbarTextOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗格设置 的本地化字符串。
        /// </summary>
        public static string TooltipChangeLayout {
            get {
                return ResourceManager.GetString("TooltipChangeLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收缩/展开 的本地化字符串。
        /// </summary>
        public static string TooltipExplodeImageBox {
            get {
                return ResourceManager.GetString("TooltipExplodeImageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏标注 的本地化字符串。
        /// </summary>
        public static string TooltipHideOverlays {
            get {
                return ResourceManager.GetString("TooltipHideOverlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一个序列 的本地化字符串。
        /// </summary>
        public static string TooltipNextDisplaySet {
            get {
                return ResourceManager.GetString("TooltipNextDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前一个序列 的本地化字符串。
        /// </summary>
        public static string TooltipPreviousDisplaySet {
            get {
                return ResourceManager.GetString("TooltipPreviousDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scale Overlay 的本地化字符串。
        /// </summary>
        public static string TooltipScaleOverlay {
            get {
                return ResourceManager.GetString("TooltipScaleOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show/Hide Colour Bar 的本地化字符串。
        /// </summary>
        public static string TooltipShowHideColorBar {
            get {
                return ResourceManager.GetString("TooltipShowHideColorBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show/Hide DICOM Overlay(s) 的本地化字符串。
        /// </summary>
        public static string TooltipShowHideDicomOverlay {
            get {
                return ResourceManager.GetString("TooltipShowHideDicomOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show/Hide Overlays 的本地化字符串。
        /// </summary>
        public static string TooltipShowHideOverlays {
            get {
                return ResourceManager.GetString("TooltipShowHideOverlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show/Hide Scale Overlay 的本地化字符串。
        /// </summary>
        public static string TooltipShowHideScaleOverlay {
            get {
                return ResourceManager.GetString("TooltipShowHideScaleOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show/Hide Shutter Overlay 的本地化字符串。
        /// </summary>
        public static string TooltipShowHideShutterOverlay {
            get {
                return ResourceManager.GetString("TooltipShowHideShutterOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show/Hide Text Overlay 的本地化字符串。
        /// </summary>
        public static string TooltipShowHideTextOverlay {
            get {
                return ResourceManager.GetString("TooltipShowHideTextOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show selected overlays 的本地化字符串。
        /// </summary>
        public static string TooltipShowOverlays {
            get {
                return ResourceManager.GetString("TooltipShowOverlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 unavailable 的本地化字符串。
        /// </summary>
        public static string Unavailable {
            get {
                return ResourceManager.GetString("Unavailable", resourceCulture);
            }
        }
    }
}
