//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer.ShelfComponentTools.PrintTool {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.ImageViewer.ShelfComponentTools.PrintTool.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 正在发送图像 的本地化字符串。
        /// </summary>
        internal static string BeginSendImage {
            get {
                return ResourceManager.GetString("BeginSendImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to convert IPresentationImage to TransformProvider 的本地化字符串。
        /// </summary>
        internal static string ConvertTransformProviderFailed {
            get {
                return ResourceManager.GetString("ConvertTransformProviderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在生成图像数据 {0}/{1} 的本地化字符串。
        /// </summary>
        internal static string CreatingImageBuffer {
            get {
                return ResourceManager.GetString("CreatingImageBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印失败，请检查胶片尺寸设置。 的本地化字符串。
        /// </summary>
        internal static string FilmError {
            get {
                return ResourceManager.GetString("FilmError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统内存不足 的本地化字符串。
        /// </summary>
        internal static string OutOfMemory {
            get {
                return ResourceManager.GetString("OutOfMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在准备发送 的本地化字符串。
        /// </summary>
        internal static string PrepareToSend {
            get {
                return ResourceManager.GetString("PrepareToSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印失败，请检查打印机设置。 的本地化字符串。
        /// </summary>
        internal static string PrinterError {
            get {
                return ResourceManager.GetString("PrinterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 准备发送 的本地化字符串。
        /// </summary>
        internal static string ReadyToSend {
            get {
                return ResourceManager.GetString("ReadyToSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送失败，失败文件数：{0}/{1} 的本地化字符串。
        /// </summary>
        internal static string SendFailure {
            get {
                return ResourceManager.GetString("SendFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送完成，成功完成{0}/{1}份 的本地化字符串。
        /// </summary>
        internal static string SendFinish {
            get {
                return ResourceManager.GetString("SendFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送 的本地化字符串。
        /// </summary>
        internal static string Sending {
            get {
                return ResourceManager.GetString("Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像打印 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户取消 的本地化字符串。
        /// </summary>
        internal static string UserCancel {
            get {
                return ResourceManager.GetString("UserCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string WarnTitle {
            get {
                return ResourceManager.GetString("WarnTitle", resourceCulture);
            }
        }
    }
}
