//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer.Tools.Synchronization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.ImageViewer.Tools.Synchronization.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 链接不同诊断 的本地化字符串。
        /// </summary>
        internal static string LabelLinkStudies {
            get {
                return ResourceManager.GetString("LabelLinkStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 断开不同诊断 的本地化字符串。
        /// </summary>
        internal static string LabelUnlinkStudies {
            get {
                return ResourceManager.GetString("LabelUnlinkStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定位线 的本地化字符串。
        /// </summary>
        internal static string MenuReferenceLines {
            get {
                return ResourceManager.GetString("MenuReferenceLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 三维定点 的本地化字符串。
        /// </summary>
        internal static string MenuSpatialLocator {
            get {
                return ResourceManager.GetString("MenuSpatialLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同步 的本地化字符串。
        /// </summary>
        internal static string MenuSynchronization {
            get {
                return ResourceManager.GetString("MenuSynchronization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序列同步 的本地化字符串。
        /// </summary>
        internal static string MenuSynchronizeStacking {
            get {
                return ResourceManager.GetString("MenuSynchronizeStacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序列/同步 的本地化字符串。
        /// </summary>
        internal static string MenuSynchronizeStackingLinkStudies {
            get {
                return ResourceManager.GetString("MenuSynchronizeStackingLinkStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 三维定点 的本地化字符串。
        /// </summary>
        internal static string PrefixSpatialLocatorTool {
            get {
                return ResourceManager.GetString("PrefixSpatialLocatorTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示交叉定位线 的本地化字符串。
        /// </summary>
        internal static string ShowCrossReferenceLines {
            get {
                return ResourceManager.GetString("ShowCrossReferenceLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示1，2定位线 的本地化字符串。
        /// </summary>
        internal static string ShowFirstAndLastReferenceLines {
            get {
                return ResourceManager.GetString("ShowFirstAndLastReferenceLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同步 的本地化字符串。
        /// </summary>
        internal static string TitleSynchronization {
            get {
                return ResourceManager.GetString("TitleSynchronization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具 的本地化字符串。
        /// </summary>
        internal static string TitleTools {
            get {
                return ResourceManager.GetString("TitleTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定位线 的本地化字符串。
        /// </summary>
        internal static string ToolbarReferenceLines {
            get {
                return ResourceManager.GetString("ToolbarReferenceLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 三维定点 的本地化字符串。
        /// </summary>
        internal static string ToolbarSpatialLocator {
            get {
                return ResourceManager.GetString("ToolbarSpatialLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序列同步 的本地化字符串。
        /// </summary>
        internal static string ToolbarSynchronization {
            get {
                return ResourceManager.GetString("ToolbarSynchronization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序列同步 的本地化字符串。
        /// </summary>
        internal static string ToolbarSynchronizeStacking {
            get {
                return ResourceManager.GetString("ToolbarSynchronizeStacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不同序列同步 的本地化字符串。
        /// </summary>
        internal static string ToolbarSynchronizeStackingLinkStudies {
            get {
                return ResourceManager.GetString("ToolbarSynchronizeStackingLinkStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定位线 的本地化字符串。
        /// </summary>
        internal static string TooltipReferenceLines {
            get {
                return ResourceManager.GetString("TooltipReferenceLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同步序列 的本地化字符串。
        /// </summary>
        internal static string TooltipSynchronizeStacking {
            get {
                return ResourceManager.GetString("TooltipSynchronizeStacking", resourceCulture);
            }
        }
    }
}
